[build]
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 flutter_sdk && \
    export PATH="$PWD/flutter_sdk/bin:$PATH" && \
    flutter precache --web && \
    flutter build web --release
  """
  publish = "build/web"

[build.environment]
  FLUTTER_WEB_USE_SKIA = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200