name: flutter_bloc_v2
description: "Proyecto de Fltuter con Bloc."
publish_to: "ManuelNZ20"
version: 0.1.0

environment:
  # sdk: ^3.10.4
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  bloc: ^9.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  # geolocator: ^10.0.0
  geolocator: ^14.0.2
  get_it: ^9.2.0
  go_router: ^10.1.0
  random_name_generator: ^1.1.0
  # uuid: ^3.0.7
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
